export interface NewsArticleMeta {
  id: string;  // slug-like id, e.g. 'why-we-built-hifive-ai'
  title: string;
  subtitle: string;
  category: string;
  author: string;
  publishedDate: string;
  readTime: string;
  description: string;  // 1-2 sentence summary
  tags: string[];
  icon: string;  // emoji icon representing the article category
  image: string;  // path to article image in /public/articles/
}

export const newsArticles: NewsArticleMeta[] = [
  {
    id: 'why-we-built-hifive-ai-revolutionizing-recruitment-through-artificial-intelligen',
    title: 'Why We Built HiFive AI: Revolutionizing Recruitment Through Artificial Intelligence',
    subtitle: 'The vision behind India\'s first AI-native hiring platform and how we\'re transforming talent acquisition',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 28, 2025',
    readTime: '8 minutes',
    description: 'The vision behind India\'s first AI-native hiring platform and how we\'re transforming talent acquisition',
    tags: ["AI Recruitment", "Recruitment Software India", "ATS India", "Hiring Automation", "HR Technology", "AI in HR", "Recruitment Innovation", "Candidate Intelligence"],
    icon: '🏢',
    image: '/articles/why-we-built-hifive-ai-revolutionizing-recruitment-through-artificial-intelligen.png',
  },
  {
    id: 'the-future-of-hiring-starts-today-how-ai-is-reshaping-talent-acquisition',
    title: 'The Future of Hiring Starts Today: How AI Is Reshaping Talent Acquisition',
    subtitle: 'A comprehensive look at how artificial intelligence is transforming every aspect of the recruitment process',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 30, 2025',
    readTime: '12 minutes',
    description: 'A comprehensive look at how artificial intelligence is transforming every aspect of the recruitment process',
    tags: ["AI Recruitment", "Future of HR", "Recruitment Technology", "Hiring Automation", "AI in HR", "Recruitment Innovation", "Talent Acquisition", "HR Analytics"],
    icon: '🧠',
    image: '/articles/the-future-of-hiring-starts-today-how-ai-is-reshaping-talent-acquisition.png',
  },
  {
    id: 'ai-is-changing-recruitment-forever-what-hr-leaders-need-to-know',
    title: 'AI Is Changing Recruitment Forever: What HR Leaders Need to Know',
    subtitle: 'Understanding the fundamental shifts in talent acquisition driven by artificial intelligence',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 31, 2025',
    readTime: '10 minutes',
    description: 'Understanding the fundamental shifts in talent acquisition driven by artificial intelligence',
    tags: ["AI Recruitment", "HR Leadership", "Recruitment Transformation", "Talent Acquisition", "AI in HR", "Recruitment Strategy", "Hiring Innovation", "Future of Work"],
    icon: '🧠',
    image: '/articles/ai-is-changing-recruitment-forever-what-hr-leaders-need-to-know.png',
  },
  {
    id: 'traditional-ats-is-broken-why-incremental-innovation-isnt-enough',
    title: 'Traditional ATS Is Broken: Why Incremental Innovation Isn\'t Enough',
    subtitle: 'Examining the fundamental limitations of legacy applicant tracking systems and the need for a new approach',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 2, 2025',
    readTime: '9 minutes',
    description: 'Examining the fundamental limitations of legacy applicant tracking systems and the need for a new approach',
    tags: ["Applicant Tracking System", "ATS India", "Recruitment Software", "AI Recruitment", "HR Technology", "Recruitment Innovation", "Hiring Automation", "Talent Acquisition"],
    icon: '🧠',
    image: '/articles/traditional-ats-is-broken-why-incremental-innovation-isnt-enough.png',
  },
  {
    id: 'top-recruitment-trends-for-2025-whats-changing-in-talent-acquisition',
    title: 'Top Recruitment Trends for 2025: What\'s Changing in Talent Acquisition',
    subtitle: 'The key shifts shaping recruitment strategies this year and how to prepare your organization',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 5, 2025',
    readTime: '11 minutes',
    description: 'The key shifts shaping recruitment strategies this year and how to prepare your organization',
    tags: ["Hiring Trends", "Recruitment Strategy", "Talent Acquisition", "AI Recruitment", "Skills-Based Hiring", "Candidate Experience", "Internal Mobility", "HR Technology"],
    icon: '📈',
    image: '/articles/top-recruitment-trends-for-2025-whats-changing-in-talent-acquisition.png',
  },
  {
    id: 'how-ai-reduces-hiring-bias-moving-beyond-good-intentions',
    title: 'How AI Reduces Hiring Bias: Moving Beyond Good Intentions',
    subtitle: 'Understanding how artificial intelligence can address unconscious bias in recruitment when implemented correctly',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 8, 2025',
    readTime: '10 minutes',
    description: 'Understanding how artificial intelligence can address unconscious bias in recruitment when implemented correctly',
    tags: ["AI Recruitment", "Hiring Bias", "Diversity and Inclusion", "Ethical AI", "Fair Hiring", "Recruitment Technology", "HR Compliance", "Unconscious Bias"],
    icon: '🧠',
    image: '/articles/how-ai-reduces-hiring-bias-moving-beyond-good-intentions.png',
  },
  {
    id: 'understanding-candidate-intelligence-the-next-evolution-in-recruitment',
    title: 'Understanding Candidate Intelligence: The Next Evolution in Recruitment',
    subtitle: 'How AI-powered candidate intelligence goes beyond resume parsing to predict candidate success',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 12, 2025',
    readTime: '11 minutes',
    description: 'How AI-powered candidate intelligence goes beyond resume parsing to predict candidate success',
    tags: ["Candidate Intelligence", "AI Recruitment", "Resume Parser", "Predictive Hiring", "Talent Assessment", "Recruitment Technology", "HR Analytics", "Quality of Hire"],
    icon: '🧠',
    image: '/articles/understanding-candidate-intelligence-the-next-evolution-in-recruitment.png',
  },
  {
    id: 'the-rise-of-ai-recruiters-how-virtual-agents-are-transforming-talent-acquisition',
    title: 'The Rise of AI Recruiters: How Virtual Agents Are Transforming Talent Acquisition',
    subtitle: 'Understanding the capabilities, limitations, and implementation considerations of AI recruiting agents',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 15, 2025',
    readTime: '10 minutes',
    description: 'Understanding the capabilities, limitations, and implementation considerations of AI recruiting agents',
    tags: ["AI Recruiters", "Recruitment Automation", "AI in HR", "Talent Acquisition", "Recruitment Technology", "Virtual Agents", "Hiring Innovation", "Future of HR"],
    icon: '🧠',
    image: '/articles/the-rise-of-ai-recruiters-how-virtual-agents-are-transforming-talent-acquisition.png',
  },
  {
    id: 'hifive-ai-v09-launch-intelligent-resume-parsing-and-candidate-ranking',
    title: 'HiFive AI v0.9 Launch: Intelligent Resume Parsing and Candidate Ranking',
    subtitle: 'Introducing our first public release with AI-powered resume understanding and predictive candidate scoring',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 18, 2025',
    readTime: '6 minutes',
    description: 'Introducing our first public release with AI-powered resume understanding and predictive candidate scoring',
    tags: ["HiFive AI", "Resume Parser", "AI Recruitment", "Product Update", "Candidate Ranking", "Recruitment Technology", "Hiring Automation", "AI in HR"],
    icon: '🚀',
    image: '/articles/hifive-ai-v09-launch-intelligent-resume-parsing-and-candidate-ranking.png',
  },
  {
    id: 'microsoft-copilot-deepens-linkedin-recruiter-integration-what-hr-teams-need-to-k',
    title: 'Microsoft Copilot Deepens LinkedIn Recruiter Integration: What HR Teams Need to Know',
    subtitle: 'Analyzing the latest updates to LinkedIn\'s AI-powered recruiting tools and their impact on enterprise talent acquisition',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 2, 2025',
    readTime: '6 minutes',
    description: 'Analyzing the latest updates to LinkedIn\'s AI-powered recruiting tools and their impact on enterprise talent acquisition',
    tags: ["LinkedIn Recruiter AI", "Enterprise AI in HR", "Recruitment Software", "Talent Sourcing", "HR Technology", "Microsoft Copilot", "Hiring Automation"],
    icon: '📊',
    image: '/articles/microsoft-copilot-deepens-linkedin-recruiter-integration-what-hr-teams-need-to-k.png',
  },
  {
    id: 'how-openais-latest-models-are-redefining-enterprise-ai-in-hr',
    title: 'How OpenAI’s Latest Models Are Redefining Enterprise AI in HR',
    subtitle: 'What the new generation of large language models means for HRMS, payroll, and recruitment platforms',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 8, 2025',
    readTime: '7 minutes',
    description: 'What the new generation of large language models means for HRMS, payroll, and recruitment platforms',
    tags: ["Enterprise AI in HR", "HR Software", "HRMS", "Payroll Software", "HR Technology", "Artificial Intelligence", "Recruitment Innovation"],
    icon: '📊',
    image: '/articles/how-openais-latest-models-are-redefining-enterprise-ai-in-hr.png',
  },
  {
    id: 'q1-2025-tech-hiring-report-navigating-the-new-normal',
    title: 'Q1 2025 Tech Hiring Report: Navigating the New Normal',
    subtitle: 'Analyzing hiring velocities, salary adjustments, and the shift toward AI-specific roles in the technology sector',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 14, 2025',
    readTime: '9 minutes',
    description: 'Analyzing hiring velocities, salary adjustments, and the shift toward AI-specific roles in the technology sector',
    tags: ["Tech Hiring Trends", "Salary Benchmarks", "Remote Hiring", "AI Engineer", "Hiring Report", "Recruitment Analytics", "Tech Layoffs", "Workforce Planning"],
    icon: '📈',
    image: '/articles/q1-2025-tech-hiring-report-navigating-the-new-normal.png',
  },
  {
    id: 'from-automation-to-autonomy-how-agentic-ai-is-automating-hiring',
    title: 'From Automation to Autonomy: How Agentic AI is Automating Hiring',
    subtitle: 'The transition from rule-based HR workflows to self-directing AI agents and what it means for your recruitment stack',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 22, 2025',
    readTime: '10 minutes',
    description: 'The transition from rule-based HR workflows to self-directing AI agents and what it means for your recruitment stack',
    tags: ["Hiring Automation", "AI Agents for HR", "Recruitment Technology", "AI in HR", "Workflow Automation", "HR Software", "Future of HR"],
    icon: '🧠',
    image: '/articles/from-automation-to-autonomy-how-agentic-ai-is-automating-hiring.png',
  },
  {
    id: 'hifive-ai-product-update-introducing-the-candidate-intelligence-module',
    title: 'HiFive AI Product Update: Introducing the Candidate Intelligence Module',
    subtitle: 'Moving beyond resumes to predict real-world job performance and team compatibility',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 28, 2025',
    readTime: '6 minutes',
    description: 'Moving beyond resumes to predict real-world job performance and team compatibility',
    tags: ["Candidate Intelligence", "Candidate Assessment", "HiFive AI", "Product Update", "Predictive Hiring", "Recruitment Software", "Quality of Hire", "HR Analytics"],
    icon: '🚀',
    image: '/articles/hifive-ai-product-update-introducing-the-candidate-intelligence-module.png',
  },
  {
    id: 'preparing-for-indias-new-labour-codes-a-compliance-roadmap-for-hr-leaders',
    title: 'Preparing for India\'s New Labour Codes: A Compliance Roadmap for HR Leaders',
    subtitle: 'Navigating the transition to the four consolidated labour codes and what your HRMS must handle',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 3, 2025',
    readTime: '11 minutes',
    description: 'Navigating the transition to the four consolidated labour codes and what your HRMS must handle',
    tags: ["HR Compliance", "Labour Code India", "Payroll India", "Payroll Software", "HRMS", "Employee Management", "Statutory Compliance", "Indian Labour Laws"],
    icon: '⚖️',
    image: '/articles/preparing-for-indias-new-labour-codes-a-compliance-roadmap-for-hr-leaders.png',
  },
  {
    id: 'q2-2025-hiring-slows-across-tech-an-analysis-of-market-correction',
    title: 'Q2 2025 Hiring Slows Across Tech: An Analysis of Market Correction',
    subtitle: 'Why tech hiring velocity is dropping and how smart companies are shifting to precision-based recruitment models',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 10, 2025',
    readTime: '8 minutes',
    description: 'Why tech hiring velocity is dropping and how smart companies are shifting to precision-based recruitment models',
    tags: ["Tech Hiring Trends", "Hiring Slowdown", "Precision Hiring", "Recruitment Analytics", "Hiring Automation", "Workforce Planning", "Recruitment Budget"],
    icon: '📈',
    image: '/articles/q2-2025-hiring-slows-across-tech-an-analysis-of-market-correction.png',
  },
  {
    id: 'ai-interviewing-best-practices-balancing-efficiency-with-human-connection',
    title: 'AI Interviewing Best Practices: Balancing Efficiency with Human Connection',
    subtitle: 'How to deploy AI interview copilots and async video tools without alienating top candidates',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 17, 2025',
    readTime: '9 minutes',
    description: 'How to deploy AI interview copilots and async video tools without alienating top candidates',
    tags: ["AI Interviews", "Interview Software", "Candidate Experience", "Ethical AI", "Recruitment Technology", "Hiring Automation", "AI in HR", "Fair Hiring"],
    icon: '🧠',
    image: '/articles/ai-interviewing-best-practices-balancing-efficiency-with-human-connection.png',
  },
  {
    id: 'the-mid-year-payroll-compliance-checklist-for-indian-startups',
    title: 'The Mid-Year Payroll Compliance Checklist for Indian Startups',
    subtitle: 'Critical TDS, PF, ESIC, and Professional Tax updates to audit before the new financial year progresses',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 24, 2025',
    readTime: '7 minutes',
    description: 'Critical TDS, PF, ESIC, and Professional Tax updates to audit before the new financial year progresses',
    tags: ["Payroll India", "Payroll Compliance", "TDS Deductions", "PF India", "ESIC Updates", "Professional Tax", "HR Compliance", "Startup HR"],
    icon: '⚖️',
    image: '/articles/the-mid-year-payroll-compliance-checklist-for-indian-startups.png',
  },
  {
    id: 'google-gemini-enterprise-updates-what-the-latest-features-mean-for-hr-teams',
    title: 'Google Gemini Enterprise Updates: What the Latest Features Mean for HR Teams',
    subtitle: 'Breaking down Google’s push into the enterprise workspace and how HR can leverage Gemini for productivity',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 30, 2025',
    readTime: '6 minutes',
    description: 'Breaking down Google’s push into the enterprise workspace and how HR can leverage Gemini for productivity',
    tags: ["Enterprise AI in HR", "HR Software", "Google Gemini", "HR Analytics", "Recruitment Technology", "HR Productivity", "AI in HR"],
    icon: '📊',
    image: '/articles/google-gemini-enterprise-updates-what-the-latest-features-mean-for-hr-teams.png',
  },
  {
    id: 'state-of-recruitment-2025-the-mid-year-benchmark-report',
    title: 'State of Recruitment 2025: The Mid-Year Benchmark Report',
    subtitle: 'Comprehensive data on time-to-hire, cost-per-hire, and AI adoption rates across the global talent market',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'July 5, 2025',
    readTime: '14 minutes',
    description: 'Comprehensive data on time-to-hire, cost-per-hire, and AI adoption rates across the global talent market',
    tags: ["Hiring Report", "Recruitment Benchmarks", "Time to Hire", "Cost Per Hire", "AI Adoption", "Skills Based Hiring", "HR Analytics", "Candidate Experience"],
    icon: '🔬',
    image: '/articles/state-of-recruitment-2025-the-mid-year-benchmark-report.png',
  },
  {
    id: 'ethical-ai-in-hiring-building-fair-algorithms-in-a-regulated-world',
    title: 'Ethical AI in Hiring: Building Fair Algorithms in a Regulated World',
    subtitle: 'Navigating the technical and legal requirements to ensure your AI recruitment tools promote equity',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'July 12, 2025',
    readTime: '11 minutes',
    description: 'Navigating the technical and legal requirements to ensure your AI recruitment tools promote equity',
    tags: ["Ethical AI", "Fair Hiring", "AI Compliance", "EU AI Act", "Hiring Bias", "Diversity and Inclusion", "Recruitment Technology", "HR Compliance"],
    icon: '🧠',
    image: '/articles/ethical-ai-in-hiring-building-fair-algorithms-in-a-regulated-world.png',
  },
  {
    id: 'hifive-ai-secures-seed-funding-to-scale-ai-first-recruitment-across-india',
    title: 'HiFive AI Secures Seed Funding to Scale AI-First Recruitment Across India',
    subtitle: 'Backed by top-tier venture capital, HiFive AI will double down on product development and enterprise expansion',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'July 18, 2025',
    readTime: '5 minutes',
    description: 'Backed by top-tier venture capital, HiFive AI will double down on product development and enterprise expansion',
    tags: ["HiFive AI", "Company News", "Startup Funding", "HR Technology India", "Recruitment Innovation", "Venture Capital", "ATS India"],
    icon: '🏢',
    image: '/articles/hifive-ai-secures-seed-funding-to-scale-ai-first-recruitment-across-india.png',
  },
  {
    id: 'the-gcc-boom-in-india-how-global-capability-centers-are-reshaping-talent-demand',
    title: 'The GCC Boom in India: How Global Capability Centers Are Reshaping Talent Demand',
    subtitle: 'Strategies for navigating the shift from cost-arbitrage to high-value product ownership in GCC hiring',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'July 24, 2025',
    readTime: '10 minutes',
    description: 'Strategies for navigating the shift from cost-arbitrage to high-value product ownership in GCC hiring',
    tags: ["GCC Hiring India", "Global Capability Centers", "Tech Hiring Trends", "India Hiring", "Salary Benchmarks India", "Talent Acquisition", "Remote Hiring", "HR Strategy"],
    icon: '📈',
    image: '/articles/the-gcc-boom-in-india-how-global-capability-centers-are-reshaping-talent-demand.png',
  },
  {
    id: 'hifive-ai-v10-launch-introducing-the-ai-interview-copilot',
    title: 'HiFive AI v1.0 Launch: Introducing the AI Interview Copilot',
    subtitle: 'Real-time transcription, smart question generation, and automated bias checks for live interviews',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'July 30, 2025',
    readTime: '7 minutes',
    description: 'Real-time transcription, smart question generation, and automated bias checks for live interviews',
    tags: ["Interview Software", "AI Interviews", "HiFive AI", "Product Update", "Recruitment Technology", "Hiring Automation", "Candidate Assessment", "HR Software"],
    icon: '🚀',
    image: '/articles/hifive-ai-v10-launch-introducing-the-ai-interview-copilot.png',
  },
  {
    id: 'ai-agents-for-hr-from-automation-to-intelligence',
    title: 'AI Agents for HR: From Automation to Intelligence',
    subtitle: 'Understanding the leap from rule-based workflows to autonomous AI agents that execute complex HR tasks',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'August 5, 2025',
    readTime: '13 minutes',
    description: 'Understanding the leap from rule-based workflows to autonomous AI agents that execute complex HR tasks',
    tags: ["AI Agents for HR", "Hiring Automation", "HR Automation", "AI in HR", "Future of HR", "HR Technology", "Recruitment Innovation"],
    icon: '🧠',
    image: '/articles/ai-agents-for-hr-from-automation-to-intelligence.png',
  },
  {
    id: 'how-a-series-b-saas-startup-reduced-time-to-hire-by-60',
    title: 'How a Series B SaaS Startup Reduced Time-to-Hire by 60%',
    subtitle: 'A customer story on leveraging HiFive AI\'s Candidate Intelligence to scale engineering teams without compromising quality',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'August 12, 2025',
    readTime: '7 minutes',
    description: 'A customer story on leveraging HiFive AI\'s Candidate Intelligence to scale engineering teams without compromising quality',
    tags: ["Customer Story", "Recruitment Software India", "Time to Hire", "Candidate Intelligence", "Quality of Hire", "ATS India", "Hiring Automation"],
    icon: '📋',
    image: '/articles/how-a-series-b-saas-startup-reduced-time-to-hire-by-60.png',
  },
  {
    id: 'workday-announces-ai-overhaul-what-it-means-for-the-enterprise-hris-market',
    title: 'Workday Announces AI Overhaul: What It Means for the Enterprise HRIS Market',
    subtitle: 'Analyzing the legacy giant\'s pivot to AI-first and the gaps that remain for modern talent acquisition',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'August 20, 2025',
    readTime: '6 minutes',
    description: 'Analyzing the legacy giant\'s pivot to AI-first and the gaps that remain for modern talent acquisition',
    tags: ["HRMS", "HR Software", "Workday", "Enterprise AI in HR", "Recruitment Technology", "Talent Acquisition", "HR Analytics"],
    icon: '📊',
    image: '/articles/workday-announces-ai-overhaul-what-it-means-for-the-enterprise-hris-market.png',
  },
  {
    id: 'esic-2025-updates-navigating-contribution-limits-and-new-digital-compliance-norm',
    title: 'ESIC 2025 Updates: Navigating Contribution Limits and New Digital Compliance Norms',
    subtitle: 'A practical guide for HR and payroll teams on the latest Employee State Insurance Corporation changes',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'August 28, 2025',
    readTime: '7 minutes',
    description: 'A practical guide for HR and payroll teams on the latest Employee State Insurance Corporation changes',
    tags: ["ESIC Updates", "Payroll India", "HR Compliance", "Payroll Software", "Employee Management", "Statutory Compliance", "Indian Labour Laws"],
    icon: '⚖️',
    image: '/articles/esic-2025-updates-navigating-contribution-limits-and-new-digital-compliance-norm.png',
  },
  {
    id: 'future-of-ai-hiring-report-2025-the-enterprise-buyers-guide',
    title: 'Future of AI Hiring Report 2025: The Enterprise Buyer\'s Guide',
    subtitle: 'A comprehensive framework for evaluating AI recruitment platforms in a crowded market',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'September 5, 2025',
    readTime: '15 minutes',
    description: 'A comprehensive framework for evaluating AI recruitment platforms in a crowded market',
    tags: ["Recruitment Software", "AI Recruitment", "HR Technology", "Enterprise AI in HR", "Applicant Tracking System", "Buyer's Guide", "HR Analytics"],
    icon: '🔬',
    image: '/articles/future-of-ai-hiring-report-2025-the-enterprise-buyers-guide.png',
  },
  {
    id: 'campus-hiring-2025-how-ai-is-replacing-mass-recruitment-drives',
    title: 'Campus Hiring 2025: How AI is Replacing Mass Recruitment Drives',
    subtitle: 'The shift from chaotic, volume-based campus events to precision, AI-driven virtual talent identification',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'September 12, 2025',
    readTime: '9 minutes',
    description: 'The shift from chaotic, volume-based campus events to precision, AI-driven virtual talent identification',
    tags: ["Campus Hiring", "Hiring Automation", "Recruitment Technology India", "Diversity and Inclusion", "AI Recruitment", "Talent Assessment", "HR Strategy"],
    icon: '📈',
    image: '/articles/campus-hiring-2025-how-ai-is-replacing-mass-recruitment-drives.png',
  },
  {
    id: 'ai-resume-screening-beyond-keywords-to-contextual-understanding',
    title: 'AI Resume Screening: Beyond Keywords to Contextual Understanding',
    subtitle: 'Why semantic search and embedding models are making traditional Boolean recruiting obsolete',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'September 22, 2025',
    readTime: '10 minutes',
    description: 'Why semantic search and embedding models are making traditional Boolean recruiting obsolete',
    tags: ["Resume Parser", "AI Recruitment", "Keyword Matching", "Semantic Search", "Recruitment Software", "Hiring Automation", "Applicant Tracking System"],
    icon: '🧠',
    image: '/articles/ai-resume-screening-beyond-keywords-to-contextual-understanding.png',
  },
  {
    id: 'hifive-ai-v12-advanced-analytics-dashboard-and-hiring-manager-self-service',
    title: 'HiFive AI v1.2: Advanced Analytics Dashboard and Hiring Manager Self-Service',
    subtitle: 'Empowering business leaders with real-time recruitment data and autonomous pipeline management',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'September 30, 2025',
    readTime: '6 minutes',
    description: 'Empowering business leaders with real-time recruitment data and autonomous pipeline management',
    tags: ["HR Analytics", "Recruitment Software", "HiFive AI", "Product Update", "Hiring Manager", "Workforce Analytics", "Recruitment Metrics"],
    icon: '🚀',
    image: '/articles/hifive-ai-v12-advanced-analytics-dashboard-and-hiring-manager-self-service.png',
  },
  {
    id: 'hifive-ai-partners-with-leading-hr-communities-to-launch-hire-ai-ready-initiativ',
    title: 'HiFive AI Partners with Leading HR Communities to Launch \'Hire AI Ready\' Initiative',
    subtitle: 'Empowering 50,000+ HR professionals with the knowledge to implement ethical and effective AI recruitment strategies',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'October 8, 2025',
    readTime: '5 minutes',
    description: 'Empowering 50,000+ HR professionals with the knowledge to implement ethical and effective AI recruitment strategies',
    tags: ["HR Technology", "Future of HR", "AI in HR", "HR Community", "Ethical AI", "Recruitment Innovation", "HR Training"],
    icon: '🏢',
    image: '/articles/hifive-ai-partners-with-leading-hr-communities-to-launch-hire-ai-ready-initiativ.png',
  },
  {
    id: 'india-hiring-report-q3-2025-insights-across-it-manufacturing-and-healthcare',
    title: 'India Hiring Report: Q3 2025 Insights Across IT, Manufacturing, and Healthcare',
    subtitle: 'Deep-dive into sector-specific talent movements, salary adjustments, and the emerging demand for hybrid skills',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'October 18, 2025',
    readTime: '12 minutes',
    description: 'Deep-dive into sector-specific talent movements, salary adjustments, and the emerging demand for hybrid skills',
    tags: ["India Hiring", "Salary Benchmarks India", "Manufacturing Hiring", "Healthcare Hiring", "IT Hiring", "Tech Hiring Trends", "Recruitment Analytics"],
    icon: '📈',
    image: '/articles/india-hiring-report-q3-2025-insights-across-it-manufacturing-and-healthcare.png',
  },
  {
    id: 'improving-candidate-quality-in-healthcare-hiring-a-case-study',
    title: 'Improving Candidate Quality in Healthcare Hiring: A Case Study',
    subtitle: 'How a regional hospital network used AI to reduce first-year nurse turnover by 35%',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'October 28, 2025',
    readTime: '7 minutes',
    description: 'How a regional hospital network used AI to reduce first-year nurse turnover by 35%',
    tags: ["Customer Story", "Healthcare Hiring", "Candidate Assessment", "Employee Retention", "Predictive Hiring", "Recruitment Technology", "HR Analytics"],
    icon: '📋',
    image: '/articles/improving-candidate-quality-in-healthcare-hiring-a-case-study.png',
  },
  {
    id: 'anthropic-claude-enterprise-updates-why-long-context-ai-matters-for-hr',
    title: 'Anthropic Claude Enterprise Updates: Why Long-Context AI Matters for HR',
    subtitle: 'Analyzing Anthropic\'s latest enterprise features and how expanded context windows transform HR document analysis',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'November 5, 2025',
    readTime: '6 minutes',
    description: 'Analyzing Anthropic\'s latest enterprise features and how expanded context windows transform HR document analysis',
    tags: ["Enterprise AI in HR", "Anthropic Claude", "HR Software", "HR Compliance", "Recruitment Technology", "AI in HR", "Document Analysis"],
    icon: '📊',
    image: '/articles/anthropic-claude-enterprise-updates-why-long-context-ai-matters-for-hr.png',
  },
  {
    id: 'remote-work-report-2025-the-return-to-office-backlash-and-global-hiring',
    title: 'Remote Work Report 2025: The Return-to-Office Backlash and Global Hiring',
    subtitle: 'Data on how RTO mandates are reshaping talent pools and accelerating remote-first hiring strategies',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'November 12, 2025',
    readTime: '10 minutes',
    description: 'Data on how RTO mandates are reshaping talent pools and accelerating remote-first hiring strategies',
    tags: ["Remote Hiring", "Remote Work", "Return to Office", "Hiring Trends", "Diversity and Inclusion", "Employer Branding", "Talent Acquisition"],
    icon: '📈',
    image: '/articles/remote-work-report-2025-the-return-to-office-backlash-and-global-hiring.png',
  },
  {
    id: 'income-tax-changes-for-fy25-26-impact-on-payroll-and-employee-ctc',
    title: 'Income Tax Changes for FY25-26: Impact on Payroll and Employee CTC',
    subtitle: 'Navigating the new tax regime slabs, standard deduction updates, and their direct implications for HR and payroll systems',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'November 18, 2025',
    readTime: '8 minutes',
    description: 'Navigating the new tax regime slabs, standard deduction updates, and their direct implications for HR and payroll systems',
    tags: ["Income Tax India", "Payroll India", "HR Compliance", "Payroll Software", "CTC Structuring", "Tax Slabs", "Employee Management"],
    icon: '⚖️',
    image: '/articles/income-tax-changes-for-fy25-26-impact-on-payroll-and-employee-ctc.png',
  },
  {
    id: 'performance-management-how-ai-is-eliminating-the-annual-review',
    title: 'Performance Management: How AI is Eliminating the Annual Review',
    subtitle: 'The transition to continuous, data-driven performance intelligence and what it means for HRMS platforms',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'November 25, 2025',
    readTime: '11 minutes',
    description: 'The transition to continuous, data-driven performance intelligence and what it means for HRMS platforms',
    tags: ["Performance Management", "HRMS", "HR Software", "AI in HR", "Employee Engagement", "HR Analytics", "Continuous Feedback"],
    icon: '🧠',
    image: '/articles/performance-management-how-ai-is-eliminating-the-annual-review.png',
  },
  {
    id: 'hifive-ai-v15-launch-introducing-ask-ai-the-natural-language-recruiting-assistan',
    title: 'HiFive AI v1.5 Launch: Introducing \'Ask AI\' - The Natural Language Recruiting Assistant',
    subtitle: 'Querying your entire talent pipeline using conversational AI with guaranteed data privacy',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'November 30, 2025',
    readTime: '6 minutes',
    description: 'Querying your entire talent pipeline using conversational AI with guaranteed data privacy',
    tags: ["HiFive AI", "Product Update", "HR Analytics", "Natural Language Processing", "Recruitment Software", "AI in HR", "Data Privacy"],
    icon: '🚀',
    image: '/articles/hifive-ai-v15-launch-introducing-ask-ai-the-natural-language-recruiting-assistan.png',
  },
  {
    id: 'hifive-ai-year-in-review-2025-milestones-and-2026-vision',
    title: 'HiFive AI Year in Review: 2025 Milestones and 2026 Vision',
    subtitle: 'Reflecting on a transformative first year of building the AI-native recruitment platform',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'December 5, 2025',
    readTime: '7 minutes',
    description: 'Reflecting on a transformative first year of building the AI-native recruitment platform',
    tags: ["HiFive AI", "Company News", "Year in Review", "Recruitment Innovation", "HR Technology", "AI Recruitment"],
    icon: '🏢',
    image: '/articles/hifive-ai-year-in-review-2025-milestones-and-2026-vision.png',
  },
  {
    id: 'employee-experience-report-2025-the-tech-fatigue-factor',
    title: 'Employee Experience Report 2025: The Tech Fatigue Factor',
    subtitle: 'How SaaS sprawl and AI overload are burning out employees - and what HR must do about it',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'December 12, 2025',
    readTime: '13 minutes',
    description: 'How SaaS sprawl and AI overload are burning out employees - and what HR must do about it',
    tags: ["Employee Experience", "HR Software", "HRMS", "SaaS Fatigue", "Employee Engagement", "HR Technology", "AI in HR"],
    icon: '🔬',
    image: '/articles/employee-experience-report-2025-the-tech-fatigue-factor.png',
  },
  {
    id: 'how-an-e-commerce-giant-scaled-blue-collar-hiring-using-ai',
    title: 'How an E-commerce Giant Scaled Blue-Collar Hiring Using AI',
    subtitle: 'Leveraging WhatsApp chatbots and voice AI to screen 10,000+ warehouse and logistics candidates monthly',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'December 18, 2025',
    readTime: '8 minutes',
    description: 'Leveraging WhatsApp chatbots and voice AI to screen 10,000+ warehouse and logistics candidates monthly',
    tags: ["Blue Collar Hiring", "Recruitment Automation", "AI Recruitment", "WhatsApp Hiring", "Voice AI", "Logistics Hiring", "High Volume Recruitment"],
    icon: '📋',
    image: '/articles/how-an-e-commerce-giant-scaled-blue-collar-hiring-using-ai.png',
  },
  {
    id: 'year-end-salary-benchmarking-what-to-expect-in-2026',
    title: 'Year-End Salary Benchmarking: What to Expect in 2026',
    subtitle: 'Forecasting compensation trends, ESOP dynamics, and the AI premium for the upcoming year',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'December 24, 2025',
    readTime: '9 minutes',
    description: 'Forecasting compensation trends, ESOP dynamics, and the AI premium for the upcoming year',
    tags: ["Salary Benchmarks", "Salary Benchmarks India", "Compensation Planning", "AI Premium", "ESOPs", "Hiring Trends", "Workforce Planning"],
    icon: '📈',
    image: '/articles/year-end-salary-benchmarking-what-to-expect-in-2026.png',
  },
  {
    id: 'sap-successfactors-ai-overhaul-integrating-generative-ai-into-core-hr',
    title: 'SAP SuccessFactors AI Overhaul: Integrating Generative AI into Core HR',
    subtitle: 'Analyzing SAP\'s \"Joule\" copilot and what it means for the legacy enterprise HRIS landscape',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'December 30, 2025',
    readTime: '6 minutes',
    description: 'Analyzing SAP\'s \"Joule\" copilot and what it means for the legacy enterprise HRIS landscape',
    tags: ["HRMS", "SAP SuccessFactors", "Enterprise AI in HR", "HR Software", "Recruitment Technology", "HR Analytics", "AI Copilot"],
    icon: '📊',
    image: '/articles/sap-successfactors-ai-overhaul-integrating-generative-ai-into-core-hr.png',
  },
  {
    id: 'hifive-ai-v20-launch-the-global-workforce-eor-module',
    title: 'HiFive AI v2.0 Launch: The Global Workforce & EOR Module',
    subtitle: 'Enabling enterprises to hire, manage, and pay global talent without setting up local entities',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 5, 2026',
    readTime: '8 minutes',
    description: 'Enabling enterprises to hire, manage, and pay global talent without setting up local entities',
    tags: ["Employer of Record", "EOR", "Global Hiring", "Remote Hiring", "Payroll Software", "HiFive AI", "Product Update", "Global Workforce"],
    icon: '🚀',
    image: '/articles/hifive-ai-v20-launch-the-global-workforce-eor-module.png',
  },
  {
    id: 'startup-hiring-predictions-for-2026-navigating-the-efficiency-era',
    title: 'Startup Hiring Predictions for 2026: Navigating the \'Efficiency Era\'',
    subtitle: 'How well-funded startups are shifting from hyper-growth headcount models to lean, AI-leveraged teams',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 10, 2026',
    readTime: '9 minutes',
    description: 'How well-funded startups are shifting from hyper-growth headcount models to lean, AI-leveraged teams',
    tags: ["Startup Hiring", "Hiring Trends", "Efficiency Era", "AI Fluency", "Compensation Planning", "Recruitment Strategy", "Tech Hiring"],
    icon: '📈',
    image: '/articles/startup-hiring-predictions-for-2026-navigating-the-efficiency-era.png',
  },
  {
    id: 'metas-llama-4-and-the-open-source-hr-revolution',
    title: 'Meta\'s Llama 4 and the Open-Source HR Revolution',
    subtitle: 'How open-weight AI models are democratizing enterprise HR tech development',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 15, 2026',
    readTime: '6 minutes',
    description: 'How open-weight AI models are democratizing enterprise HR tech development',
    tags: ["Enterprise AI in HR", "Open Source AI", "Meta Llama", "HR Technology", "Data Privacy", "Recruitment Software", "AI Architecture"],
    icon: '📊',
    image: '/articles/metas-llama-4-and-the-open-source-hr-revolution.png',
  },
  {
    id: 'how-ai-is-transforming-employee-onboarding-from-paperwork-to-experience',
    title: 'How AI is Transforming Employee Onboarding: From Paperwork to Experience',
    subtitle: 'Using agentic AI to personalize the first 90 days and accelerate time-to-productivity',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 22, 2026',
    readTime: '10 minutes',
    description: 'Using agentic AI to personalize the first 90 days and accelerate time-to-productivity',
    tags: ["Employee Onboarding", "AI in HR", "HRMS", "Employee Engagement", "HR Technology", "Learning Management System", "Recruitment Retention"],
    icon: '🧠',
    image: '/articles/how-ai-is-transforming-employee-onboarding-from-paperwork-to-experience.png',
  },
  {
    id: 'india-pf-provident-fund-updates-2026-navigating-new-kyc-and-threshold-rules',
    title: 'India PF (Provident Fund) Updates 2026: Navigating New KYC and Threshold Rules',
    subtitle: 'What HR and payroll teams must know about the latest EPFO mandates taking effect this year',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 28, 2026',
    readTime: '7 minutes',
    description: 'What HR and payroll teams must know about the latest EPFO mandates taking effect this year',
    tags: ["PF India", "EPFO Updates", "Payroll India", "HR Compliance", "Payroll Software", "Employee Management", "Statutory Compliance"],
    icon: '⚖️',
    image: '/articles/india-pf-provident-fund-updates-2026-navigating-new-kyc-and-threshold-rules.png',
  },
  {
    id: 'hifive-ai-expands-to-southeast-asia-new-singapore-office',
    title: 'HiFive AI Expands to Southeast Asia: New Singapore Office',
    subtitle: 'Establishing our APAC hub to serve the booming demand for AI recruitment in SEA and ANZ markets',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'January 31, 2026',
    readTime: '5 minutes',
    description: 'Establishing our APAC hub to serve the booming demand for AI recruitment in SEA and ANZ markets',
    tags: ["HiFive AI", "Company News", "Singapore Office", "APAC Expansion", "Global Hiring", "HR Technology"],
    icon: '🏢',
    image: '/articles/hifive-ai-expands-to-southeast-asia-new-singapore-office.png',
  },
  {
    id: 'global-talent-mobility-report-2026-the-rise-of-digital-nomad-visas',
    title: 'Global Talent Mobility Report 2026: The Rise of Digital Nomad Visas',
    subtitle: 'How changes in immigration law are reshaping cross-border talent acquisition strategies',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 5, 2026',
    readTime: '14 minutes',
    description: 'How changes in immigration law are reshaping cross-border talent acquisition strategies',
    tags: ["Global Talent Mobility", "Digital Nomad Visa", "Remote Hiring", "Employer of Record", "HR Compliance", "Global Payroll", "Cross Border Hiring"],
    icon: '🔬',
    image: '/articles/global-talent-mobility-report-2026-the-rise-of-digital-nomad-visas.png',
  },
  {
    id: 'ai-in-performance-management-moving-from-tracking-to-coaching',
    title: 'AI in Performance Management: Moving from Tracking to Coaching',
    subtitle: 'How next-gen AI tools are transforming managers into strategic coaches rather than evaluators',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 10, 2026',
    readTime: '10 minutes',
    description: 'How next-gen AI tools are transforming managers into strategic coaches rather than evaluators',
    tags: ["Performance Management", "HRMS", "AI in HR", "Employee Coaching", "HR Analytics", "Employee Development", "Future of HR"],
    icon: '🧠',
    image: '/articles/ai-in-performance-management-moving-from-tracking-to-coaching.png',
  },
  {
    id: 'how-a-fintech-startup-scaled-compliance-hiring-using-ai',
    title: 'How a FinTech Startup Scaled Compliance Hiring Using AI',
    subtitle: 'Reducing risk and accelerating time-to-hire for highly regulated AML and KYC roles',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 14, 2026',
    readTime: '7 minutes',
    description: 'Reducing risk and accelerating time-to-hire for highly regulated AML and KYC roles',
    tags: ["Customer Story", "FinTech Hiring", "Compliance Hiring", "Candidate Intelligence", "Risk Management", "Recruitment Software"],
    icon: '📋',
    image: '/articles/how-a-fintech-startup-scaled-compliance-hiring-using-ai.png',
  },
  {
    id: 'microsoft-viva-insights-ai-upgrades-the-future-of-workplace-analytics',
    title: 'Microsoft Viva Insights AI Upgrades: The Future of Workplace Analytics',
    subtitle: 'Analyzing Microsoft\'s deeper push into AI-driven employee productivity and wellbeing tracking',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 19, 2026',
    readTime: '6 minutes',
    description: 'Analyzing Microsoft\'s deeper push into AI-driven employee productivity and wellbeing tracking',
    tags: ["Microsoft Viva", "Workplace Analytics", "Employee Experience", "HR Software", "AI in HR", "Employee Wellbeing", "Enterprise AI"],
    icon: '📊',
    image: '/articles/microsoft-viva-insights-ai-upgrades-the-future-of-workplace-analytics.png',
  },
  {
    id: 'the-rise-of-fractional-hiring-in-tech-leveraging-ai-for-elastic-workforces',
    title: 'The Rise of Fractional Hiring in Tech: Leveraging AI for Elastic Workforces',
    subtitle: 'How startups and SMBs are using AI to source and manage part-time, high-impact executives',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 24, 2026',
    readTime: '8 minutes',
    description: 'How startups and SMBs are using AI to source and manage part-time, high-impact executives',
    tags: ["Fractional Hiring", "Startup Hiring", "Hiring Trends", "Recruitment Technology", "Executive Search", "AI Recruitment", "Elastic Workforce"],
    icon: '📈',
    image: '/articles/the-rise-of-fractional-hiring-in-tech-leveraging-ai-for-elastic-workforces.png',
  },
  {
    id: 'gig-worker-laws-in-india-the-code-on-social-security-implementation',
    title: 'Gig Worker Laws in India: The Code on Social Security Implementation',
    subtitle: 'What platforms and HR teams must know as India finally enforces social security for gig workers',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'February 28, 2026',
    readTime: '8 minutes',
    description: 'What platforms and HR teams must know as India finally enforces social security for gig workers',
    tags: ["Gig Worker Laws India", "Code on Social Security", "HR Compliance", "Payroll India", "Contingent Workforce", "Freelancer Compliance"],
    icon: '⚖️',
    image: '/articles/gig-worker-laws-in-india-the-code-on-social-security-implementation.png',
  },
  {
    id: 'hifive-ai-v23-launch-autonomous-sourcing-agents-go-ga',
    title: 'HiFive AI v2.3 Launch: Autonomous Sourcing Agents Go GA',
    subtitle: 'Moving from AI-assisted search to fully autonomous talent identification and outreach',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 3, 2026',
    readTime: '7 minutes',
    description: 'Moving from AI-assisted search to fully autonomous talent identification and outreach',
    tags: ["HiFive AI", "Product Update", "Autonomous Sourcing", "Recruitment Automation", "Talent Sourcing", "AI Recruiters", "HR Technology"],
    icon: '🚀',
    image: '/articles/hifive-ai-v23-launch-autonomous-sourcing-agents-go-ga.png',
  },
  {
    id: 'explainable-ai-xai-in-recruitment-why-black-boxes-are-dead',
    title: 'Explainable AI (XAI) in Recruitment: Why Black Boxes Are Dead',
    subtitle: 'The technical and legal necessity of understanding exactly why your AI rejected a candidate',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 8, 2026',
    readTime: '11 minutes',
    description: 'The technical and legal necessity of understanding exactly why your AI rejected a candidate',
    tags: ["Explainable AI", "XAI", "Ethical AI", "AI Compliance", "Recruitment Technology", "AI Recruitment", "HR Legal"],
    icon: '🧠',
    image: '/articles/explainable-ai-xai-in-recruitment-why-black-boxes-are-dead.png',
  },
  {
    id: 'q1-2026-hiring-salary-benchmark-report-the-ai-talent-premium-peaks',
    title: 'Q1 2026 Hiring & Salary Benchmark Report: The AI Talent Premium Peaks',
    subtitle: 'Comprehensive data showing the widening compensation gap between AI-fluent and traditional tech roles',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 12, 2026',
    readTime: '13 minutes',
    description: 'Comprehensive data showing the widening compensation gap between AI-fluent and traditional tech roles',
    tags: ["Salary Benchmarks", "Salary Benchmarks India", "AI Premium", "Tech Hiring Trends", "Hiring Report", "Compensation Planning", "AI Talent"],
    icon: '🔬',
    image: '/articles/q1-2026-hiring-salary-benchmark-report-the-ai-talent-premium-peaks.png',
  },
  {
    id: 'hifive-ai-wins-top-hr-innovation-award-at-shrm-india-2026',
    title: 'HiFive AI Wins \"Top HR Innovation\" Award at SHRM India 2026',
    subtitle: 'Recognized for revolutionizing recruitment with autonomous AI agents and global workforce solutions',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 17, 2026',
    readTime: '4 minutes',
    description: 'Recognized for revolutionizing recruitment with autonomous AI agents and global workforce solutions',
    tags: ["HiFive AI", "Company News", "SHRM India", "HR Award", "Recruitment Innovation", "HR Technology"],
    icon: '🏢',
    image: '/articles/hifive-ai-wins-top-hr-innovation-award-at-shrm-india-2026.png',
  },
  {
    id: 'the-talent-scarcity-in-green-tech-esg-roles',
    title: 'The Talent Scarcity in Green Tech & ESG Roles',
    subtitle: 'How AI can help identify transferable skills to fill the massive gap in sustainability talent',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 22, 2026',
    readTime: '9 minutes',
    description: 'How AI can help identify transferable skills to fill the massive gap in sustainability talent',
    tags: ["Green Tech Hiring", "ESG Roles", "Transferable Skills", "AI Recruitment", "Sustainability Talent", "Candidate Intelligence", "Skills Based Hiring"],
    icon: '📈',
    image: '/articles/the-talent-scarcity-in-green-tech-esg-roles.png',
  },
  {
    id: 'google-gemini-20-enterprise-what-the-multimodal-upgrade-means-for-hr',
    title: 'Google Gemini 2.0 Enterprise: What the Multimodal Upgrade Means for HR',
    subtitle: 'Analyzing Google\'s push into video, audio, and agentic capabilities for enterprise workflows',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 26, 2026',
    readTime: '6 minutes',
    description: 'Analyzing Google\'s push into video, audio, and agentic capabilities for enterprise workflows',
    tags: ["Google Gemini", "Enterprise AI in HR", "Multimodal AI", "HR Technology", "L&D", "AI Interviews", "Recruitment Technology"],
    icon: '📊',
    image: '/articles/google-gemini-20-enterprise-what-the-multimodal-upgrade-means-for-hr.png',
  },
  {
    id: 'ai-and-internal-mobility-building-the-talent-marketplace',
    title: 'AI and Internal Mobility: Building the Talent Marketplace',
    subtitle: 'How AI-powered talent marketplaces are replacing traditional job postings to retain top talent',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 30, 2026',
    readTime: '10 minutes',
    description: 'How AI-powered talent marketplaces are replacing traditional job postings to retain top talent',
    tags: ["Internal Mobility", "Talent Marketplace", "HRMS", "AI in HR", "Employee Retention", "Skills Graph", "Workforce Planning"],
    icon: '🧠',
    image: '/articles/ai-and-internal-mobility-building-the-talent-marketplace.png',
  },
  {
    id: 'how-a-global-logistics-firm-reduced-cross-border-hiring-time-by-50',
    title: 'How a Global Logistics Firm Reduced Cross-Border Hiring Time by 50%',
    subtitle: 'Leveraging HiFive AI\'s Global Workforce module to deploy talent across 12 countries in record time',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'March 31, 2026',
    readTime: '7 minutes',
    description: 'Leveraging HiFive AI\'s Global Workforce module to deploy talent across 12 countries in record time',
    tags: ["Customer Story", "Global Hiring", "Employer of Record", "Cross Border Hiring", "Recruitment Automation", "HiFive AI", "Global Workforce"],
    icon: '📋',
    image: '/articles/how-a-global-logistics-firm-reduced-cross-border-hiring-time-by-50.png',
  },
  {
    id: 'the-complete-guide-to-payroll-software-india-2026-buyers-edition',
    title: 'The Complete Guide to Payroll Software India: 2026 Buyer\'s Edition',
    subtitle: 'Evaluating HRMS and payroll platforms for the new era of AI compliance and global workforces',
    category: 'Compliance & HR Laws',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 5, 2026',
    readTime: '15 minutes',
    description: 'Evaluating HRMS and payroll platforms for the new era of AI compliance and global workforces',
    tags: ["Payroll Software India", "HRMS", "HR Compliance", "Buyer's Guide", "Payroll India", "TCO", "Employee Management"],
    icon: '⚖️',
    image: '/articles/the-complete-guide-to-payroll-software-india-2026-buyers-edition.png',
  },
  {
    id: 'ai-vs-traditional-ats-a-comprehensive-comparison-for-2026',
    title: 'AI vs Traditional ATS: A Comprehensive Comparison for 2026',
    subtitle: 'A feature-by-feature breakdown of why legacy systems are losing to AI-native platforms',
    category: 'AI in HR',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 12, 2026',
    readTime: '12 minutes',
    description: 'A feature-by-feature breakdown of why legacy systems are losing to AI-native platforms',
    tags: ["Applicant Tracking System", "ATS India", "AI Recruitment", "Recruitment Software", "HR Technology", "Hiring Automation", "AI vs Traditional"],
    icon: '🧠',
    image: '/articles/ai-vs-traditional-ats-a-comprehensive-comparison-for-2026.png',
  },
  {
    id: 'the-state-of-employee-engagement-in-2026-moving-beyond-surveys',
    title: 'The State of Employee Engagement in 2026: Moving Beyond Surveys',
    subtitle: 'Why annual engagement surveys are dying and being replaced by AI-driven continuous listening',
    category: 'Research Reports',
    author: 'HiFive AI Research Team',
    publishedDate: 'April 20, 2026',
    readTime: '12 minutes',
    description: 'Why annual engagement surveys are dying and being replaced by AI-driven continuous listening',
    tags: ["Employee Engagement", "HR Analytics", "AI in HR", "Employee Experience", "Sentiment Analysis", "HR Software", "Continuous Feedback"],
    icon: '🔬',
    image: '/articles/the-state-of-employee-engagement-in-2026-moving-beyond-surveys.png',
  },
  {
    id: 'meta-apple-and-google-ai-hardware-updates-implications-for-hr-tech',
    title: 'Meta, Apple, and Google AI Hardware Updates: Implications for HR Tech',
    subtitle: 'How on-device AI and spatial computing will change how we interact with workplace software',
    category: 'Industry News',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 5, 2026',
    readTime: '6 minutes',
    description: 'How on-device AI and spatial computing will change how we interact with workplace software',
    tags: ["Enterprise AI in HR", "HR Technology", "AI Hardware", "Spatial Computing", "Data Privacy", "Future of Work", "HRMS"],
    icon: '📊',
    image: '/articles/meta-apple-and-google-ai-hardware-updates-implications-for-hr-tech.png',
  },
  {
    id: 'how-ai-improved-recruiter-productivity-a-quantitative-analysis',
    title: 'How AI Improved Recruiter Productivity: A Quantitative Analysis',
    subtitle: 'Measuring the exact time savings and output multipliers achieved by deploying AI recruitment tools',
    category: 'Customer Stories',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 12, 2026',
    readTime: '8 minutes',
    description: 'Measuring the exact time savings and output multipliers achieved by deploying AI recruitment tools',
    tags: ["Customer Story", "Recruiter Productivity", "Hiring Automation", "Recruitment Metrics", "Time Management", "AI Recruitment"],
    icon: '📋',
    image: '/articles/how-ai-improved-recruiter-productivity-a-quantitative-analysis.png',
  },
  {
    id: 'the-founders-dilemma-when-to-hire-your-first-hr-leader',
    title: 'The Founder\'s Dilemma: When to Hire Your First HR Leader',
    subtitle: 'Strategic advice for startup CEOs on building the talent foundation before the scale breaks',
    category: 'Company News',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 20, 2026',
    readTime: '7 minutes',
    description: 'Strategic advice for startup CEOs on building the talent foundation before the scale breaks',
    tags: ["Startup HR", "Founder Advice", "HR Strategy", "Recruitment Strategy", "Startup Hiring", "HR Leadership"],
    icon: '🏢',
    image: '/articles/the-founders-dilemma-when-to-hire-your-first-hr-leader.png',
  },
  {
    id: 'q2-2026-hiring-trends-report-the-stabilization-of-the-ai-market',
    title: 'Q2 2026 Hiring Trends Report: The Stabilization of the AI Market',
    subtitle: 'How the initial frenzy around AI hiring is maturing into sustainable, specialized demand',
    category: 'Hiring Trends',
    author: 'HiFive AI Research Team',
    publishedDate: 'May 28, 2026',
    readTime: '9 minutes',
    description: 'How the initial frenzy around AI hiring is maturing into sustainable, specialized demand',
    tags: ["Hiring Trends", "AI Talent Market", "Tech Hiring", "MLOps", "Salary Benchmarks", "India Hiring", "Recruitment Analytics"],
    icon: '📈',
    image: '/articles/q2-2026-hiring-trends-report-the-stabilization-of-the-ai-market.png',
  },
  {
    id: 'hifive-ai-v25-the-closed-loop-talent-graph',
    title: 'HiFive AI v2.5: The Closed-Loop Talent Graph',
    subtitle: 'Connecting recruitment intelligence with post-hire performance data to create self-improving AI models',
    category: 'Product Updates',
    author: 'HiFive AI Research Team',
    publishedDate: 'June 3, 2026',
    readTime: '7 minutes',
    description: 'Connecting recruitment intelligence with post-hire performance data to create self-improving AI models',
    tags: ["HiFive AI", "Product Update", "Closed-Loop Talent Graph", "Recruitment AI", "Performance Data"],
    icon: '🚀',
    image: '/articles/hifive-ai-v25-the-closed-loop-talent-graph.png',
  },
];